### ISSUE TITLE
[EPIC] Migrate MANAGED Tables

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#103]
Related issues to this epic:

- [ ] https://github.com/databrickslabs/ucx/issues/1204
- [ ] https://github.com/databrickslabs/ucx/issues/334
- [x] https://github.com/databrickslabs/ucx/issues/332
- [ ] https://github.com/databrickslabs/ucx/issues/903
- [x] https://github.com/databrickslabs/ucx/issues/927
- [ ] https://github.com/databrickslabs/ucx/issues/1065
- [x] https://github.com/databrickslabs/ucx/issues/1218
- [ ] https://github.com/databrickslabs/ucx/issues/1219
- [x] https://github.com/databrickslabs/ucx/issues/1221

**Comment by FastLee** [comment]
Marked table as migrated on the assessment report
Default Target Schema
Allow Specifying a Target Schema, Target DB by DB

**Comment by FastLee** [comment]
Read target catalog and database from the "databases" table
Update migration status and migration errors on the "databases" table.
