### ISSUE TITLE
[EPIC] Improve permissions handling

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem statement

Improve:
- [ ] https://github.com/databrickslabs/ucx/issues/886
- [ ] https://github.com/databrickslabs/ucx/issues/875
- [ ] https://github.com/databrickslabs/ucx/issues/883
- [ ] https://github.com/databrickslabs/ucx/issues/892
- [ ] https://github.com/databrickslabs/ucx/issues/415
- [ ] https://github.com/databrickslabs/ucx/issues/321

### Proposed Solution

-
