### ISSUE TITLE
[EPIC] Q2

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1490]
Relative priorities:

- [ ] https://github.com/databrickslabs/ucx/issues/1491
- [ ] https://github.com/databrickslabs/ucx/issues/103
- [ ] https://github.com/databrickslabs/ucx/issues/1085
- [ ] https://github.com/databrickslabs/ucx/issues/1204
- [ ] https://github.com/databrickslabs/ucx/issues/891
- [ ] https://github.com/databrickslabs/ucx/issues/1485
- [ ] https://github.com/databrickslabs/ucx/issues/1124
- [ ] https://github.com/databrickslabs/ucx/issues/1492
- [ ] https://github.com/databrickslabs/ucx/issues/1528
