### ISSUE TITLE
[EPIC] Migrate SQL Warehouses & Redash Dashboards

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#1491]
Related issues:

- [x] https://github.com/databrickslabs/ucx/issues/1474
- [x] https://github.com/databrickslabs/ucx/issues/1503
- [x] https://github.com/databrickslabs/ucx/issues/1533
- [x] https://github.com/databrickslabs/ucx/issues/1537
- [x] https://github.com/databrickslabs/ucx/issues/1535
- [x] https://github.com/databrickslabs/ucx/issues/1536
- [x] https://github.com/databrickslabs/ucx/issues/1107
- [x] https://github.com/databrickslabs/ucx/issues/102

This issue has a hidden risk on the availability of Redash APIs to facilitate the migration. We have to assume that the SDK for Redash Queries and Dashboards is only 50% complete and would require 2-3pw overhead of getting the relevant APIs for us to be even usable. This is Redash-to-Redash.

Redash-to-Lakeview upgrade is out of scope.

**Comment by nfx** [comment]
2pw-4pw
