### ISSUE TITLE
[EPIC] Migrate `EXTERNAL` tables from cloud storage accounts

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#333]
Related issues:
- [x] #1430 by @FastLee 
- [x] https://github.com/databrickslabs/ucx/issues/670 by @qziyuan 
- [x] https://github.com/databrickslabs/ucx/issues/910 by @FastLee 
- [ ] https://github.com/databrickslabs/ucx/issues/1488 by @FastLee 
- [x] #939 by @nkvuong 
- [x] https://github.com/databrickslabs/ucx/issues/323 by @JCZuurmond 
- [x] https://github.com/databrickslabs/ucx/issues/1192 by @HariGS-DB 
- [x] #910
- [ ] #1391
- [x] #1384
- [x] #889 by @qziyuan 
- [x] https://github.com/databrickslabs/ucx/issues/341 by @nkvuong 
- [x] https://github.com/databrickslabs/ucx/issues/94 by @pritishpai 
- [x] https://github.com/databrickslabs/ucx/issues/900
- [x] https://github.com/databrickslabs/ucx/pull/680
- [x] https://github.com/databrickslabs/ucx/issues/100
- [x] https://github.com/databrickslabs/ucx/issues/899
- [x] https://github.com/databrickslabs/ucx/issues/340
- [x] https://github.com/databrickslabs/ucx/issues/887 
- [x] https://github.com/databrickslabs/ucx/issues/907
- [x] Verify that we have the external locations for these tables
- [x] Use `SYNC` to upgrade these tables "in place". Use the default or override catalog.database destination. Update the source table with "upgraded_to" property.

**Comment by pohlposition** [comment]
Also update the source table with a description that includes "this table is deprecated" which will show the table name with a strikethrough when it is attempted to be queried in SQL Query Editor:
https://community.databricks.com/t5/warehousing-analytics/unity-catalog-quot-this-table-is-deprecated-quot-functionality/td-p/55340

**Comment by nfx** [comment]
This is the remaining epic for Q1
