### ISSUE TITLE
Migrate `EXTERNAL` tables from AWS Glue or other external HMS

### ISSUE THREAD

**Issue by nfx** [databrickslabs/ucx#337]
See https://github.com/databrickslabs/ucx/issues/317

# Definition of done:

- [x] full end-user documentation - README.md + revise [this document](https://github.com/databrickslabs/ucx/blob/main/docs/external_hms_glue.md) - #1458
- [x] integration test for AWS Glue - #1408, #1368
- [x] integration test for MSSQL - #1408, #1368
- [x] integration test for assessment -> table-migration for external tables #1408, #1460

**Comment by pohlposition** [comment]
@nfx 
Is this an Epic to cover 317 and other future issues around this?

**Comment by nfx** [comment]
main bulk of external HMS work is done, closing this epic. Rest to be fixed as bugs
