### ISSUE TITLE
[EPIC]: Figure out storage credential permissions for external locations

### ISSUE THREAD

**Issue by nkvuong** [databrickslabs/ucx#893]
Automate creation of Storage credentials:

- [x] https://github.com/databrickslabs/ucx/issues/337
- [x] https://github.com/databrickslabs/ucx/issues/862
- [x] https://github.com/databrickslabs/ucx/issues/339
- [x] https://github.com/databrickslabs/ucx/issues/881
- [x] https://github.com/databrickslabs/ucx/issues/879
- [x] https://github.com/databrickslabs/ucx/issues/862
- [x] https://github.com/databrickslabs/ucx/issues/693
- [x] https://github.com/databrickslabs/ucx/issues/339

**Comment by nfx** [comment]
Moving:
- https://github.com/databrickslabs/ucx/issues/875

to next quarter:
- https://github.com/databrickslabs/ucx/issues/1485

**Comment by nfx** [comment]
Moving:
- https://github.com/databrickslabs/ucx/issues/670

to:
- https://github.com/databrickslabs/ucx/issues/333

**Comment by nfx** [comment]
closing this epic as complete.
